
version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres_db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 3030:80
    environment:
      PGADMIN_DEFAULT_EMAIL: juan@perez.com
      PGADMIN_DEFAULT_PASSWORD: crazy_juan

# volumes:
#   postgres_db: {
#     driver: local
#   }

